#!/bin/sh 

#PBS -V 
#PBS -S /bin/sh 
#PBS -N prep1
#PBS -A FluxTraining_flux
#PBS -l qos=flux
#PBS -q flux
#PBS -l mem=3750mb
#PBS -M cja@umich.edu 
#PBS -m abe 
#PBS -j oe 

# Navigate to the directory submitted from
if [ -n "$PBS_O_WORKDIR" ]; then cd $PBS_O_WORKDIR; fi
pwd
 
# Execute the commands

echo + "date"
date

echo + "hostname"
hostname

echo + "printenv | grep ^PBS"
printenv | grep ^PBS

if [ -n "$PBS_JOBID" ]; then
	echo + "qstat -f $PBS_JOBID"
	qstat -f $PBS_JOBID
fi
